### ISSUE TITLE
In revenue by region widget, refresh button is inactive mode.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#770] opened 2017-12-13 10:04 UTC
**Description:**
In revenue by region widget, refresh button is inactive mode.

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Steps to reproduce:**
1.Create new dashboard called Sales Statistics.
2.Create a new page called Sales-stats-test.
3.Drag and drop revenue by region widget.
4. You can notice that refresh button is not in active mode.
![screenshot from 2017-12-13 14-24-09](https://user-images.githubusercontent.com/30232477/33933204-04acaaf6-e01b-11e7-8da6-d56cb3f9497a.png)

**Comment by lasanthaS** [comment] 2017-12-13 14:04
Refresh button is getting activated when the chart is changed by clicking on an area. This button is to reset the chart once u are drill-down it to other state. Hence the normal behavior is to keep the button in disabled mode. 

Hence closing this issue as **Not a bug**.

**Closed by lasanthaS** 2017-12-13 14:04 UTC
